# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4cf19f1021c5a2cf883af8b32855f5d7394a275fa2314bffd1e645bfa97ba489b67be2632a721f36015ab8124e9d484ce9f7afcfc47e42ff2ada64a5cec09e2

test:
  secret_key_base: 73084aa30a0e541f5699f61af5e8f2798010a1d944aa1426a3484ad66901258bb81d27078aa93d64bf6cb0cd75c6256f50a1efb74cb2e34926fdeee6770bbc2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
